apiVersion: v1
kind: Service
metadata:
  name: writer
spec:
  selector:
    app: writer
  ports:
    - protocol: TCP
      name: writer
      port: 5003
      targetPort: 5003
    - name: actuator
      port: 5103
      targetPort: 5103

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5103"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: writer
          image: borntonight/writer:1
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
              name: http-api
            - containerPort: 5103
              name: actuator
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 30
            httpGet:
              path: /actuator/health/liveness
              port: 5103
              scheme: HTTP
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            httpGet:
              path: /actuator/health/readiness
              port: 5103
              scheme: HTTP
            timeoutSeconds: 10
            failureThreshold: 1
            successThreshold: 1
          env:
            - name: SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SERVICE_HOST_WRITER
            - name: SPRING_ADMIN_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_HOST
            - name: SPRING_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_USER
            - name: SPRING_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_HOST
            - name: KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_TOPIC
            - name: KAFKA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_CLIENT_ID
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_GROUP_ID
            - name: LOGSTASH_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: LOGSTASH_HOST
